apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  "bbd-realm.json": {{ index .Values "realm-secret" "bbd-realm" | toJson | b64enc | quote }}
  "external-realm.json": {{ index .Values "realm-secret" "external-realm" | toJson | b64enc | quote }}
  "master-realm.json": {{ index .Values "realm-secret" "master-realm" | toJson | b64enc | quote }}