apiVersion: v1
kind: Secret
metadata:
  name: realm-secret-bbd
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  bbd-realm.json: {{ tpl (.Files.Get "files/bbd-realm.json") . | b64enc }}