apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  master-realm.json: {{ tpl (.Files.Get "files/master-realm.json") . | b64enc }}
  bbd-realm.json: {{ tpl (.Files.Get "files/bbd-realm.json") . | b64enc }}
  external-realm.json: {{ tpl (.Files.Get "files/external-realm.json") . | b64enc }}

