dependencies:
- name: keycloak
  alias: official-keycloak
  repository: https://codecentric.github.io/helm-charts
  version: 5.1.1
- name: postgresql
  alias: official-postgresql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 5.3.9
  condition: keycloak.cloudsql.disabled
