dependencies:
- name: keycloak
  alias: official-keycloak
  repository: https://codecentric.github.io/helm-charts
  version: 4.14.1
- name: postgresql
  alias: official-postgresql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 0.15.0
  condition: keycloak.cloudsql.enabled
