official-keycloak:
  fullnameOverride: official-kc
  keycloak:
    extraInitContainers: |
      - name: theme-provider
        image: gcr.io/simple-step-project/keycloak-theme:0.1.0
        imagePullPolicy: Always
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying theme..."
            cp -R /mytheme/* /theme
        volumeMounts:
          - name: theme
            mountPath: /theme

    {{- if .Values.global.cloudsql.enabled }}
    extraContainers: |
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command:
          - /cloud_sql_proxy
        args:
          - -instances={{ .Values.global.cloudsql.project }}:{{ .Values.global.cloudsql.region }}:{{ .Values.global.cloudsql.instance }}=tcp:5432
          - -credential_file=/secrets/cloudsql/credentials.json
        volumeMounts:
          - name: cloudsql-creds
            mountPath: /secrets/cloudsql
            readOnly: true
    {{- end }}

    extraVolumeMounts: |
      - name: theme
        mountPath: /opt/jboss/keycloak/standalone/deployments
      - name: realm-secret
        mountPath: "/realm/"
        readOnly: true

    extraVolumes: |
      - name: theme
        emptyDir: {}
      - name: realm-secret
        secret:
          secretName: realm-secret
      {{- if .Values.global.cloudsql.enabled }}          
      - name: cloudsql-creds
        secret:
          secretName: cloudsql-instance-credentials
      {{- end }}

    # extraArgs: -Dkeycloak.import=/realm/realm.json
    extraArgs: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/realm -Dkeycloak.migration.strategy=IGNORE_EXISTING

    password: "admin"
    persistence:
      # Disable deployment of the PostgreSQL chart
      deployPostgres: false

      # The database vendor. Can be either "postgres", "mysql", "mariadb", or "h2"
      # dbVendor: H2
      dbVendor: postgres

      ## The following values only apply if "deployPostgres" is set to "false"

      # Optionally specify an existing secret
      existingSecret: official-pg
      existingSecretKey: postgres-password
      # existingSecretKey: postgresql-password

      dbName: keycloak
      {{- if .Values.global.cloudsql.enabled }}
      dbHost: 127.0.0.1
      {{- else }}
      dbHost: official-pg
      {{- end }}
      # dbHost: {{ .Values.environment.cloudsql | ternary "127.0.0.1" "official-pg" }}
      dbPort: 5432 # 5432 is PostgreSQL's default port. For MySQL it would be 3306
      dbUser: keycloak

      # Only used if no existing secret is specified. In this case a new secret is created
      # dbPassword: keycloak
    service:
      annotations:
        fabric8.io/ingress.name: "mykeycloak"
        fabric8.io/expose: "true"

# https://github.com/helm/helm/issues/4490
keycloak:
  persistence:
    deployPostgres: false

global:
  postgres:
    enabled: true

official-postgresql:
  fullnameOverride: official-pg
  # postgresqlUsername: keycloak
  # postgresqlPassword: password
  # postgresqlDatabase: keycloak
  postgresUser: keycloak
  postgresPassword: password
  postgresDatabase: keycloak
